### ISSUE TITLE
removeTrack

### ISSUE THREAD

**Issue by mp1pro** [rttolentino/Jamming#14]
We can make removeTrack shorter by using .filter to return the results without the deleted track.

```
  removeTrack(track) {
    let tracks = this.state.playlistTracks;
    tracks = tracks.filter(currentTrack => currentTrack.id !== track.id);

    this.setState({playlistTracks: tracks});
}
```

**Comment by rttolentino** [comment]
Completely forgot about ".filter()" when I originally wrote this. That makes things so much easier... Pushed update via "issue_14" branch, merged into master in #20.
