### ISSUE TITLE
Config.js

### ISSUE THREAD

**Issue by mp1pro** [rttolentino/Jamming#16]
great use of config.js and .gitignore files for protecting your credentials. You can also place a note in the readme.md on how to set it up for anyone else that wants to use the project.

**Comment by rttolentino** [comment]
Moved the default "README.md" made by Create React App to "React_README.md" and created a more useful "README.md" specifically for this project. Also, modified ".config.js" to be ".config.json", and updated "Spotify.js" to use the new file. Pushed update via "issue_16" branch, merged into main in #18.
