### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [rttolentino/Jamming#17]
Great attention to detail and execution. The app works great as it should. Did not not find any major errors. I would only suggest looking into other methods to manipulate arrays. Having the right method can save a lot of time. Here is a documentation for handling arrays.

https://www.w3schools.com/jsref/jsref_obj_array.asp

**Comment by rttolentino** [comment]
Thanks for the critique! I'm going over the issues you noted and making changes as needed. I definitely need to get more familiar with all the array functions, so I've saved the link you provided. Thanks, again.

**Comment by rttolentino** [comment]
All issues resolved. Thanks again for looking over my code!
